export enum AuditEventType {
  USER_CREATED = "UserCreated",
  USER_UPDATED = "UserUpdated",
  USER_DELETED = "UserDeleted",
  USER_REGISTERED = "UserRegistered",
  USER_LOGGED_IN = "UserLoggedIn",
  USER_LOGGED_OUT = "UserLoggedOut",
  LOGIN_ERROR = "UserLoginError",
  USER_PASSWORD_RESET = "UserPasswordReset",
  USER_PASSWORD_RESET_REQUESTED = "UserPasswordResetRequested",
  USER_PASSWORD_CHANGED = "UserPasswordChanged",
  USER_EMAIL_VERIFIED = "UserEmailVerified",
  USER_EMAIL_CHANGED = "UserEmailChanged",
  USER_ROLE_ASSIGNED = "UserRoleAssigned",
  USER_ROLE_REMOVED = "UserRoleRemoved",
  USER_PROFILE_UPDATED = "UserProfileUpdated",
  USER_ACCOUNT_LOCKED = "UserAccountLocked",
  USER_ACCOUNT_UNLOCKED = "UserAccountUnlocked",
  USER_PROFILE_VIEWED = "UserProfileViewed",
}

export enum AuditEventActorType {
  SYSTEM = "system",
  USER = "user",
  ADMIN = "admin",
  SERVICE = "service",
}

export enum AuditEventTargetEntityType {
  REGISTER_USER = "register_user",
  REGISTER_USER_ERROR = "register_user_error",
  VALIDATE_USER = "validate_user",
  USER_PROFILE = "user_profile",
  USER_ACCOUNT = "user_account",
  ADMIN_ACTION = "admin_action",
  SYSTEM_EVENT = "system_event",
  SERVICE_CALL = "service_call",
  ROLE_ASSIGNMENT = "role_assignment",
  ROLE_REMOVAL = "role_removal",
  PASSWORD_CHANGE = "password_change",
  EMAIL_VERIFICATION = "email_verification",
  EMAIL_CHANGE = "email_change",
  ACCOUNT_LOCK = "account_lock",
  ACCOUNT_UNLOCK = "account_unlock",
  LOGIN_EVENT = "login_event",
  LOGOUT_EVENT = "logout_event",
  PROFILE_VIEW = "profile_view",
  USER_PROFILE_UPDATED = "user_profile_updated",
}
