export enum AccessStep {
  AUTHENTICATION = "AUTHENTICATION",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  F2A_VERIFICATION = "F2A_VERIFICATION",
  ONBOARDING = "ONBOARDING",
  READY = "READY",
  SELECT_TENANT = "SELECT_TENANT",
  SELECT_SUBSCRIPTION = "SELECT_SUBSCRIPTION",
  SEND_INVITATIONS = "SEND_INVITATIONS",
  COMPLETED = "COMPLETED",
}

export enum AccessStepStatus {
  PENDING = "PENDING", // serve azione
  BLOCKED = "BLOCKED", // non può proseguire
  COMPLETED = "COMPLETED", // step concluso
  FAILED = "FAILED",
}

export enum AccessStatus {
  SUCCESS = "SUCCESS",
  FAILURE = "FAILURE",
  PENDING = "PENDING",
}

export enum AccessAction {
  RESEND_VERIFICATION_EMAIL = "RESEND_VERIFICATION_EMAIL",
  START_ONBOARDING = "START_ONBOARDING",
  CONTINUE_ONBOARDING = "CONTINUE_ONBOARDING",
  COMPLETE_ONBOARDING = "COMPLETE_ONBOARDING",
  ACCESS_APP = "ACCESS_APP",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  VERIFY_2FA = "VERIFY_2FA",
  SHOW_TENANT_SELECTION = "SHOW_TENANT_SELECTION",
}

export enum TokenType {
  EMAIL_VERIFICATION = 0,
  PASSWORD_RESET = 1,
  ACCOUNT_ACTIVATION = 2,
  ACCESS = 3,
}

export enum VerificationError {
  TOKEN_EXPIRED = 0,
  TOKEN_INVALID = 1,
  TOKEN_ALREADY_USED = 2,
  USER_NOT_FOUND = 3,
}

export enum VerificationTokenType {
  EMAIL_VERIFICATION = 0,
  PASSWORD_RESET = 1,
  ACCOUNT_ACTIVATION = 2,
}
