import {
  MigrationInterface,
  QueryRunner,
  Table,
  TableColumn,
  TableForeignKey,
} from "typeorm";

// Clean migration derived from libs/common/src/profile/job-role.entity.ts
export class RecreateJobRolesFromEntity20251201220000
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const hasTable = await queryRunner.hasTable("job_roles");

    if (!hasTable) {
      await queryRunner.createTable(
        new Table({
          name: "job_roles",
          columns: [
            {
              name: "id",
              type: "int",
              isPrimary: true,
              isGenerated: true,
              generationStrategy: "increment",
            },
            { name: "tenant_id", type: "int", isNullable: true },
            { name: "name", type: "varchar", length: "100" },
            { name: "is_custom", type: "boolean", default: false },
            { name: "is_default", type: "boolean", default: false },
            {
              name: "created_at",
              type: "timestamp",
              default: "CURRENT_TIMESTAMP",
            },
            {
              name: "updated_at",
              type: "timestamp",
              default: "CURRENT_TIMESTAMP",
            },
          ],
        })
      );
    } else {
      const table = await queryRunner.getTable("job_roles");
      // Ensure required columns exist and match types
      const ensureColumn = async (col: TableColumn) => {
        const exists = table?.findColumnByName(col.name);
        if (!exists) {
          await queryRunner.addColumn("job_roles", col);
        }
      };
      await ensureColumn(
        new TableColumn({ name: "tenant_id", type: "int", isNullable: true })
      );
      await ensureColumn(
        new TableColumn({
          name: "name",
          type: "varchar",
          length: "100",
          isNullable: false,
        })
      );
      await ensureColumn(
        new TableColumn({
          name: "is_custom",
          type: "boolean",
          default: false as any,
        })
      );
      await ensureColumn(
        new TableColumn({
          name: "is_default",
          type: "boolean",
          default: false as any,
        })
      );
      await ensureColumn(
        new TableColumn({
          name: "created_at",
          type: "timestamp",
          default: "CURRENT_TIMESTAMP",
        })
      );
      await ensureColumn(
        new TableColumn({
          name: "updated_at",
          type: "timestamp",
          default: "CURRENT_TIMESTAMP",
        })
      );

      // Normalize NOT NULL for name (backfill then set)
      await queryRunner.query(
        `UPDATE job_roles SET name = COALESCE(name, label) WHERE name IS NULL;`
      );
      await queryRunner.query(
        `UPDATE job_roles SET name = 'Senza nome' WHERE name IS NULL;`
      );
      await queryRunner.query(
        `ALTER TABLE job_roles ALTER COLUMN name SET NOT NULL;`
      );

      // Ensure id auto-generation
      const idCol = table?.findColumnByName("id");
      if (idCol && !idCol.isGenerated) {
        try {
          await queryRunner.query(
            `ALTER TABLE job_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`
          );
        } catch {
          await queryRunner.query(
            `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'job_roles_id_seq') THEN CREATE SEQUENCE job_roles_id_seq; END IF; END$$;`
          );
          await queryRunner.query(
            `ALTER TABLE job_roles ALTER COLUMN id SET DEFAULT nextval('job_roles_id_seq');`
          );
          await queryRunner.query(
            `ALTER SEQUENCE job_roles_id_seq OWNED BY job_roles.id;`
          );
        }
        await queryRunner.query(
          `SELECT setval(COALESCE((SELECT pg_get_serial_sequence('job_roles','id')),'job_roles_id_seq'), COALESCE((SELECT MAX(id) FROM job_roles),0)+1, false);`
        );
      }
    }

    // Create FK to tenants only if table exists (optional coupling)
    if (
      (await queryRunner.hasTable("job_roles")) &&
      (await queryRunner.hasTable("tenants"))
    ) {
      const jobRolesTable = await queryRunner.getTable("job_roles");
      const tenantFK = jobRolesTable?.foreignKeys.find((fk) =>
        fk.columnNames.includes("tenant_id")
      );
      if (!tenantFK) {
        await queryRunner.createForeignKey(
          "job_roles",
          new TableForeignKey({
            columnNames: ["tenant_id"],
            referencedTableName: "tenants",
            referencedColumnNames: ["id"],
            onDelete: "CASCADE",
          })
        );
      }
    }

    // Ensure profiles has job_role_id with FK
    const profilesTable = await queryRunner.getTable("profiles");
    if (profilesTable && !profilesTable.findColumnByName("job_role_id")) {
      await queryRunner.addColumn(
        "profiles",
        new TableColumn({ name: "job_role_id", type: "int", isNullable: true })
      );
    }
    if (profilesTable) {
      const existingFK = profilesTable.foreignKeys.find((fk) =>
        fk.columnNames.includes("job_role_id")
      );
      if (!existingFK) {
        await queryRunner.createForeignKey(
          "profiles",
          new TableForeignKey({
            columnNames: ["job_role_id"],
            referencedTableName: "job_roles",
            referencedColumnNames: ["id"],
            onDelete: "SET NULL",
          })
        );
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop FK from profiles
    const profilesTable = await queryRunner.getTable("profiles");
    const profileFK = profilesTable?.foreignKeys.find((fk) =>
      fk.columnNames.includes("job_role_id")
    );
    if (profileFK) await queryRunner.dropForeignKey("profiles", profileFK);
    if (profilesTable?.findColumnByName("job_role_id"))
      await queryRunner.dropColumn("profiles", "job_role_id");

    // Drop FK from job_roles to tenants
    const jobRolesTable = await queryRunner.getTable("job_roles");
    const tenantFK = jobRolesTable?.foreignKeys.find((fk) =>
      fk.columnNames.includes("tenant_id")
    );
    if (tenantFK) await queryRunner.dropForeignKey("job_roles", tenantFK);

    // Do not drop job_roles table to preserve data; optional:
    // await queryRunner.dropTable("job_roles");
  }
}
